// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `send`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LlmEngine>>
abstract class LlmEngine implements RustOpaqueInterface {
  /// Answers a host call: [error] when set, [payload] otherwise.
  bool answer({
    required PlatformInt64 callId,
    required String payload,
    String? error,
  });

  /// The end of a response body.
  bool endBody({required PlatformInt64 streamId, String? error});

  factory LlmEngine() => RustLib.instance.api.crateApiLlmEngineNew();

  /// A chunk of a response body.
  bool pushBody({required PlatformInt64 streamId, required List<int> chunk});

  /// Asks `__fl.dispatch(method, payload)`; answered by a result message.
  bool request({
    required PlatformInt64 reqId,
    required String method,
    required String payload,
  });

  /// Starts the runtime. Everything it says arrives on [sink], in order.
  Stream<HostMessage> start();
}

/// A message from the engine. A flat struct rather than an enum with fields,
/// so the Dart side needs no generated sealed classes.
class HostMessage {
  final HostMessageKind kind;
  final PlatformInt64 id;
  final String name;
  final String payload;
  final Uint8List? body;

  const HostMessage({
    required this.kind,
    required this.id,
    required this.name,
    required this.payload,
    this.body,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      id.hashCode ^
      name.hashCode ^
      payload.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostMessage &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id &&
          name == other.name &&
          payload == other.payload &&
          body == other.body;
}

/// What a [HostMessage] is.
enum HostMessageKind {
  /// [HostMessage::id] is the request; [HostMessage::payload] its JSON result.
  result,

  /// [HostMessage::id] is the call to answer; [HostMessage::name] what to do.
  hostCall,

  /// [HostMessage::name] happened; no answer.
  notify,

  /// [HostMessage::payload] is an event, as JSON.
  event,

  /// [HostMessage::name] is the level.
  log,

  /// The engine is gone; [HostMessage::payload] says why.
  fatal,
}
